name: Build Image and Publish to Dockerhub & GPR

on:
  push:
    branches: [ test-build, action ]
  release:
    types: [ created ]

jobs:

  binary:
    name: Build Golang project
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      -
        run: go version
      -
        name: Check out code into the Go module directory
        uses: actions/checkout@v2
      -
        name: Build
        run: make build
      -
        name: Archive artifacts for frpc
        uses: actions/upload-artifact@v1
        with:
          name: frpc
          path: bin/frpc
      -
        name: Archive artifacts for frps
        uses: actions/upload-artifact@v1
        with:
          name: frps
          path: bin/frps

  image:
    name: Build Image from Dockerfile and binaries
    runs-on: ubuntu-latest
    needs: binary
    steps:
      # environment
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # get release name
      -
        name: Echo
        run: |
          echo ${{ github.ref }} > RELEASE_NAME
          cat RELEASE_NAME
      # download binaries of frpc and frps
      -
        name: Download binary of frpc
        uses: actions/download-artifact@v2
        with:
          name: frpc
          path: bin/frpc
      -
        name: Download binary of frps
        uses: actions/download-artifact@v2
        with:
          name: frps
          path: bin/frps
      # geneate tags
      -
        name: Prepare envs
        id: prep
        run: |
          echo "dockerfiles/Dockerfile-for-frpc" > DOCKERFILE_FRPC_PATH
          echo "dockerfiles/Dockerfile-for-frps" > DOCKERFILE_FRPS_PATH
          echo "fatedier/frpc:${{ steps.bump.outputs.new_tag }}" > TAG_FRPC
          echo "fatedier/frps:${{ steps.bump.outputs.new_tag }}" > TAG_FRPS
          echo "ghcr.io/${{ github.repository}}/frpc:${{steps.bump.outputs.tag}}" > TAG_FRPC_GPR
          echo "ghcr.io/${{ github.repository}}/frps:${{steps.bump.outputs.tag}}" > TAG_FRPS_GPR
      # build images
      -
        name: Build Images
        run: |
          # for Docker hub
          docker build --file $(cat DOCKERFILE_FRPC_PATH) --tag $(cat TAG_FRPC) .
          docker build --file $(cat DOCKERFILE_FRPS_PATH) --tag $(cat TAG_FRPS) .
          # for GPR
          docker build --file $(cat DOCKERFILE_FRPC_PATH) --tag $(cat TAG_FRPC_GPR) .
          docker build --file $(cat DOCKERFILE_FRPS_PATH) --tag $(cat TAG_FRPS_GPR) .
      # push to dockerhub
      -
        name: Publish to Dockerhub
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push $(cat TAG_FRPC)
          docker push $(cat TAG_FRPC)
      # push to gpr
      -
        name: Publish to GPR
        run: |
          echo ${{ secrets.GPR_TOKEN }} | docker login ghcr.io --username ${{ github.repository_owner }} --password-stdin
          docker push $(cat TAG_FRPC_GPR)
          docker push $(cat TAG_FRPS_GPR)
